#server:
#  port: ${SERVER_PORT}

spring:
  application:
    name: "UserService"
  profiles:
    # https://codesarray.com/view/Multiple-application-properties-file-in-spring-boot
    active: "dev"
    default: "dev"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
  datasource:
    url: "jdbc:mysql://localhost:3306/userservice?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

logging:
  level:
    org:
      springframework:
        security: "trace"

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans"
  info:
    env:
      enabled: "true"

#Actuator
# /actuator/info
info:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    anything: "absolutely anything"
#    we can read/reference any property already declared above
#    https://www.mscharhag.com/spring/property-references
    applicationName: ${spring.application.name}


# Eureka Client
# https://cloud.spring.io/spring-cloud-netflix/reference/html/#spring-cloud-eureka-server-standalone-mode
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"